# Generated by Django 4.1.2 on 2022-10-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
