# Generated by Django 4.1.2 on 2022-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_is_published_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(blank=True, max_length=460),
        ),
    ]
